### PR TITLE
Update to Pydantic v2.

### PR DESCRIPTION
**Pull request by eseglem**
Think its all working, still want to do more double checking.

### CODE REVIEW

**Comment by bitner** [comment]
Hey @eseglem, is there any additional tests or review that you are hoping to have to merge this PR? It's working fine for me in my tests, would like to get a version with pydantic 2 support that I could pin to. Let me know if there's anything I can do to help push this along.

**Comment by eseglem** [comment]
Trying to remember what all there was. 

I know there were still a few `# type: ignore` statements that I wanted to see if I could correct. Been playing around with them some, and making a little progress. `Accenti` and `Casei` have been the main source of issues. They are weird generics, and Mypy does not like variable types.

Also worth reviewing the latest version of the spec, I haven't looked at it in a while and there may be some tweaks that should get integrated. 

When updating to pydantic 2.4 to 2.5, a handful of tests start to fail. Pydantic seems to always nest the `PropertyRef` inside `CharacterExpression` when reading from JSON, and forced it on the text transformer before. But does not now. 

Before: 
```
json: CharacterExpression(root=PropertyRef(property='geometry'))
text: CharacterExpression(root=PropertyRef(property='geometry'))
```

After:
```
json: CharacterExpression(root=PropertyRef(property='geometry'))
text: PropertyRef(property='geometry')
```

I feel like the updated text one is probably more correct. But need to figure out the right order for all the definitions to make them all work nicely.

**Comment by eseglem** [comment]
Managed to get through most of the typing / testing issues, but ended up with a few things I am not totally happy with. 

Rather than fighting with the Generics, ended up with separate Casei and Accenti classes for each CharacterExpression and PatternExpression. Potentially annoying when using the classes directly, but fine for parsing. It should be possible to do with Generics, but it was causing a bunch of complications and this avoids them.

Ideally would like the make CharacterLiteral a subtype of string and have it single quote itself, but the problem is getting it to still be like a `StrictStr`. It would remove the need for the extra `CharacterClause` and `PatternExpression` classes which basically only exists to wrap the string in single quotes.

**Comment by eseglem** [comment]
I think this is probably good enough for now. There are a few other things to explore, but nothing that prevents moving forward here. 

Closes: #40

**Pull request merged**
